branches:
   except:
      - gh-pages

language: python

python:
 - "2.7"

install: 
  - pip install coveralls
  - pip install pytest-cov
  - pip install -r requirements.txt
  - python setup.py install

script:
  - "PYTHONPATH=`PWD` py.test --cov trump"

after_sucess:
  - coveralls