branches:
   except:
      - gh-pages
      - prototype

language: python

python:
 - "2.7"

install: 
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - py.test -cov trump

after_sucess:
  - coveralls
